### ISSUE TITLE
Version `1.0.0` Roadmap

### ISSUE THREAD

**Issue by 13g10n** [13g10n/aiogram-forms#10]
# Roadmap
I'm on the way to update it and make first stable release.

Planned features:
- [ ] **Menus** with ability to link items to either forms or other menus (pretty big, but extrimely useful)
- [ ] Add more types of forms, generic fields and validators
- [ ] Add more languages
- [ ] Add pretty and useful documentation with more examples

Also, I'm planning to perform some technical improvements:
- [ ] Cover all codebase with tests
- [ ] Add flake8 or even black for better formatting
- [ ] Extend type hints

*Feel free to add feature requests or any other comments in this thread.*
